defaultBaseImage: ghcr.io/chainguard-dev/apko:v0.1.2@sha256:5504f2a95018e3d8a52d80d9e1a128c6ea337581808ff9fe96f5628ce2336350

builds:
- id: peribolos
  dir: .
  main: ./main.go
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -extldflags "-static"
