name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  COSIGN_EXPERIMENTAL: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504 # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

    - name: Set up Go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Install ko
      uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d # v0.5

    - name: Install cosign
      uses: sigstore/cosign-installer@09a077b27eb1310dcfb21981bee195b30ce09de0 # v2.2.0

    - name: Log into ghcr.io
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v1.14.1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        make build-sign-images
